name: git push into another repo to deploy to vercel

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    container: pandoc/latex
    steps:
      - uses: actions/checkout@v2
      - name: Install mustache (to update the date)
        run: apk add ruby && gem install mustache
      - name: creates output
        run: sh ./build.sh

      - name: Get commit message
        id: get_commit_message
        run: echo "::set-output name=commit_message::$(git log --format=%B -n 1 ${{ github.sha }})"

      - name: Pushes to another repository
        id: push_directory
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.AUTO_KEY }}
          COMMIT_MESSAGE: ${{ steps.get_commit_message.outputs.commit_message }}
        with:
          source-directory: 'output'
          destination-github-username: 'seung365'
          destination-repository-name: 'alphamail-frontend'
          user-email: ${{ secrets.OFFICIAL_ACCOUNT_EMAIL}}
          commit-message: ${{ env.COMMIT_MESSAGE }}
          target-branch: main

      - name: Test get variable exported by push-to-another-repository
        run: echo $DESTINATION_CLONED_DIRECTORY
